CREATE INDEX RESERVATION_STATUS_IDX
ON RESERVATION (STATUS);

CREATE INDEX TRANSPORT_TYPE_IDX
ON TRAVEL (TRANSPORT_TYPE);

CREATE INDEX RESERVATION_TIME_IDX
ON RESERVATION (RESERVATION_TIME);

CREATE INDEX USER_ROLE_IDX
ON USER (USER_TYPE);

CREATE INDEX PAYMENT_AMOUNT_IDX
ON PAYMENT (AMOUNT);

CREATE INDEX CITY_NAME_IDX
ON CITY (CITY_NAME);

CREATE INDEX TICKET_PRICE_IDX
ON TRAVEL (PRICE);

CREATE INDEX REPORT_CATEGORY_IDX
ON REPORT (REPORT_CATEGORY);

CREATE INDEX IDX_USER_ID
ON RESERVATION (USER_ID);

CREATE INDEX IDX_TICKET_ID
ON RESERVATION (TICKET_ID);

CREATE INDEX IDX_TRAVEL_ID
ON TICKET (TRAVEL_ID);

CREATE INDEX IDX_CITY_ID
ON TERMINAL (CITY_ID);

CREATE INDEX IDX_RESERVATION_ID
ON RESERVATIONCHANGE (RESERVATION_ID);
